### ISSUE TITLE
Add new API

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#42]
Add these 2 API as proof of concept with a schema and make them follow the same path as Nominatim and Geonames to see if we abstract well the logic.

https://www.nrcan.gc.ca/science-and-data/science-and-research/earth-sciences/geography/topographic-information/web-services/geolocation-service/17304
https://geogratis.gc.ca/services/geolocation/en/locate?q=ott*

https://www.nrcan.gc.ca/science-and-data/science-and-research/earth-sciences/geography/topographic-information/web-services/delimitation-service/17217
https://geogratis.gc.ca/services/delimitation/en/nts?q=000L

**Comment by jolevesq** [comment]
Related to #18

**Comment by David-Henandez-nrcan** [comment]
In order to adapt the application to this services, the function for standard fields (without lookup) has to be modified to acquire nested fields inside successive dictionaries.
Once the modification was implemented and validated, both services (schemas included) were easily added on the list of options in the application.
